### ISSUE TITLE
Edge cases with Percentiles

### ISSUE THREAD

**Issue by RKelln** [montanaflynn/stats#15]
I believe there are some errors with the `Percentiles()` edge cases. 

Passing 0 as the percent will cause an error as will a small set of data and a small percentage (such that the `c[i-1]` is out of bounds because `i = 0`.

I'm not sure the best approach to fix this, as picking which index is quite critical for the correct result, but I think this might work?
```
index := (percent / 100) * float64(len(c) - 1)
```
And then use `c[i]` and `c[i+1]` later on. Using `c[i+1]` would be dangerous with `input.Len() == 1` and maybe in the case of 99.9 percent and few values?

**Comment by montanaflynn** [comment]
Thanks for the :bug: report! I reproduced a panic and that's definitely not ok.

What were you expecting from the output? It might make sense to return an error when given a 0 percent argument like we do for empty data. 

###### Output from reproduced panic for posterity:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/montanaflynn/stats.Percentile(0x82026f910, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0)
	/dev/go/src/github.com/montanaflynn/stats/percentile.go:28 +0x290
main.main()
	/dev/go/src/github.com/montanaflynn/stats/examples/main.go:46 +0x10c5
exit status 2
```

**Comment by RKelln** [comment]
I'd expect 0% to act like minimum (and 100% to be the maximum).

**Comment by montanaflynn** [comment]
What do you mean by minimum? Can you give me an example with real data and the expected result?

As far as I know there is no concept of a 0% percentile.

**Comment by RKelln** [comment]
In my mind 50th percentile == median, 0th == first/min, 100th == last/max. 

Wikipedia says:
"One definition of percentile, often given in texts, is that the P-th percentile (0 < P <= 100) of a list of N ordered values (sorted from least to greatest) is the smallest value in the list such that P percent of the data is less than or equal to that value."

So no 0th there, but it seems reasonable that 0 would just be the first sorted value (as would 0.00001 or any other small percentile in all but the largest datasets). 

You could return an error to force people to use Min() instead but I could see a use case where the percentile is set dynamically from 0 to 100 for some reason and its easier to just include 0 rather than force > 0. Not a big deal to me however.

**Comment by RKelln** [comment]
Any news? Thanks.

**Comment by montanaflynn** [comment]
Sorry @RKelln I've been super busy. Immediately after the issue was raised I added some sanity checks to avoid the panics (5bd4bff9c2bc5ed0f73abbcbffcfae45b27abc47) and now, after some thought, I think I would rather have the use of `Min()` be decided upon by the end-user. 

Thanks again for the bug report and discussion!

**Comment by RKelln** [comment]
Thanks @montanaflynn. However this still doesn't handle the cases where `i = 0` and you do a lookup of `c[i-1]` which can happen with a low percentage or few values. Passing zero was just the easiest way to trigger it.

We could add a check for i == 0 but it smells wrong. Hm, basing it on the other stats library I use [descriptive_statistics](https://github.com/thirtysixthspan/descriptive_statistics/blob/master/lib/descriptive_statistics/percentile.rb) it would look like:
```go
func Percentile(input Float64Data, percent float64) (percentile float64, err error) {

  if input.Len() == 0 || percent == 0 {
    return math.NaN(), EmptyInput
  }

  if input.Len() == 1 {
    return input[0], nil
  }

  // Start by sorting a copy of the slice
  c := sortedCopy(input)

  if percent == 100.0 {
    return c[c.Len()-1], nil
  }

  rank := percent / 100.0 * (c.Len() - 1)
  rank_floor := float64ToInt(rank)
  lower := c[rank_floor]
  upper := c[rank_floor + 1]
  return lower + ((upper - lower) * (rank - float64(rank_floor))), nil
  
}
```
This has a different algorithm though, more similar to the way Excel seems to do it?
