### ISSUE TITLE
Exported error values

### ISSUE THREAD

**Issue by Kunde21** [montanaflynn/stats#16]
Instead of the error values being generated within the functions, globally-defined errors would allow error handling in the calling function to be done without parsing the error string.  

This error is generated in many places, but there's no way to compare two error values without comparing the string itself.  Additionally, there's no guarantee that two "Empty input errors" have the exact same error string.
```go
	if input.Len() == 0 {
		return 0, errors.New("Input must not be empty")
	}
```

If all of those errors are collected into a set of exported constants:
```go 

type struct StatErr {
      err string
}

func (s StatErr) Error() string {
        return err
}

const (
        EmptyArrayError = StatErr{"Empty input can't be processed"}
        ...
)
```

That way an error value can be identified by these constants:

In the code:
```go
	if input.Len() == 0 {
		return 0, EmptyArrayError
	}
```
In the call:
```go
	v, err := stat.Mean(input)
	if err == stat.EmptyArrayError {
		//Handle the specific error
	}
```

This would clean up the error returns in the library and make error handling easier for anyone using it.

**Comment by montanaflynn** [comment]
This seems like a good addition, would you be able to submit a pull request?

**Comment by Kunde21** [comment]
Sure, I can work on this next week.  I'll create PR when I have the basics of it coded.
