### ISSUE TITLE
Please Provide Annotated Release Tags

### ISSUE THREAD

**Issue by MTecknology** [montanaflynn/stats#28]
This package is used by Gitea which is a package I'm currently working to get into Debian. This means I get to do a review of all build dependencies. While working through your project, I saw that tags are used to mark releases, but they are not being annotated.

Unannotated release tags end up causing some headaches for packaging systems that monitor upstream activity--mostly for new releases--because the information is missing from 'git describe'. To annotate a tag, it just needs the -a flag passed. (git tag -a).

If you're willing to, it's possible to update the current tags (or just latest) with annotation. I've included some links [1] [2] that explain the process.

If you choose not to update tags, it would still be hugely appreciated if you could use annotated tags in the future.

[1] http://sartak.org/2011/01/replace-a-lightweight-git-tag-with-an-annotated-tag.html
[2] http://stackoverflow.com/questions/5002555/can-a-lightweight-tag-be-converted-to-an-annotated-tag

**Comment by montanaflynn** [comment]
Thanks for the detailed request! I'll take a look at the links later tonight and see if I can add annotations to the current releases and add it to my release process for the future.

**Comment by MTecknology** [comment]
Excellent, thanks!
