### ISSUE TITLE
semver tags, please

### ISSUE THREAD

**Issue by jeffallen** [montanaflynn/stats#37]
Could you please tag v0.3.0 so that vgo can find it and use it?

See: https://research.swtch.com/vgo

Thank you.

**Comment by montanaflynn** [comment]
Done, added a new release and tag `0.3.0` which is valid semver, although it does not have the v prefix as seen in the vgo docs. 

I couldn't find any guide on using vgo to test if it would work without the prefix. Hopefully it works with traditional semver so I won't have to duplicate existing tags.
