### ISSUE TITLE
Hi, I was thinking of implementing a norm class (normal distribution probability density function, point percentile,  etc. ), should I add it as a pull request?

### ISSUE THREAD

**Issue by rvchess** [montanaflynn/stats#55]

**Comment by montanaflynn** [comment]
Yes that would be great!

Maybe it could be similar to this, as Go doesn't have classes?

https://github.com/montanaflynn/stats/blob/5391ebe88c319ab997c4483517123a1b4929dcc8/regression.go

**Comment by montanaflynn** [comment]
Closed with #56
