### ISSUE TITLE
[Suggestion] Calculate Quartile from the instance of Float64Data

### ISSUE THREAD

**Issue by pararang** [montanaflynn/stats#60]
Nice package, I am using it right now. And I found an inconsistency while calculating the quartiles. Any reason why we must pass the data/input to calculate Quartile? Why not use the instance. If there is no specific reason, I suggest adding the `Quartiles` method on the Float64Data's struct without any input, but use the current instance, like we use Mean(), Max(), etc.

Suggestion: 
```go
func (f Float64Data) Quartiles() (Quartiles, error) {
	return Quartile(f)
}
```
If this is possible, I will make the MR.

**Comment by montanaflynn** [comment]
Hello @pararang, this is a good catch, there is no reason why the `data.Quartile` method needs the input. The suggestion to add `Quartiles()` is good since it wouldn't be a breaking change. Make a pull request and I'll take a look.

**Comment by pararang** [comment]
Alright, I'm working on it.

**Comment by pararang** [comment]
Submitted on PR #61,  Please take a look, @montanaflynn.

**Comment by montanaflynn** [comment]
Thanks! I merged it and will issue a new release version soon.
