### ISSUE TITLE
percentile is having issue

### ISSUE THREAD

**Issue by ws6** [montanaflynn/stats#62]
https://github.com/montanaflynn/stats/blob/8e3445df250b3bdc0f4f1edb6379e547efb825b2/percentile.go#L26

it should be : index := (percent/100)*float64(len(c)-1) + 1
according to the wiki  https://www.calculatorsoup.com/calculators/statistics/percentile-calculator.php
 r = (p/100) * (n - 1) + 1

to produce the bug, try this dataset 
0.67, 0.999, 1
percent = 25

**Comment by Tarliton** [comment]
Hello, another test case:
```
dataset: 1, 2
percentile: 50

this library returns: 1

calculator soup returns: 1.5
```
Thank you

**Comment by montanaflynn** [comment]
I'm not sure what algorithm calculatoroup uses exactly but according to wikipedia there is no common definition of percentile:

https://en.wikipedia.org/wiki/Percentile#Definitions

The stats library actually contains two algorithms:

`stats.Percentile` and `stats.PercentileNearestRank`

I would be happy to look at a pull request with suggested changes or a new function that matches calculatorsoup.

Also Wolframalpha shows 50th percentile of [1,2] as 1: 

https://www.wolframalpha.com/input/?i=50th+percentile+for+%5B1%2C2%5D

**Comment by Tarliton** [comment]
It seems that Wolframalpha uses the index position to calculate percentile.

Using an example from this repository test:
```go
m, _ := stats.Percentile([]float64{43, 54, 56, 61, 62, 66}, 90)
if m != 64.0 {
	t.Errorf("%.1f != %.1f", m, 64.0)
}
```

Wolframalpha returns 66:
https://www.wolframalpha.com/input/?i=90th+percentile+for+%5B+43%2C+54%2C+56%2C+61%2C+62%2C+66%5D

Percentile 83 and 84 is where the value changes:
https://www.wolframalpha.com/input/?i=83th+percentile+for+%5B+43%2C+54%2C+56%2C+61%2C+62%2C+66%5D

https://www.wolframalpha.com/input/?i=84th+percentile+for+%5B+43%2C+54%2C+56%2C+61%2C+62%2C+66%5D

Well, I consider my question answered.
There is no common definition of percentile as you, quoting wikipedia, said.

Thank you.
