### ISSUE TITLE
panic: sync: negative WaitGroup counter in dbscan.go

### ISSUE THREAD

**Issue by lastzero** [montanaflynn/stats#70]
We use your library for our open-source photo app, in particular the DBSCAN implementation. Thanks for providing it!

While it works great for me, a developer reported issues with panics in `dbscan.go`, line 251. Seems `w.Done()` may be called too often, probably depending on input data. Couldn't reproduce it with my local samples.

Our related code and GitHub issue:
- https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/faces.go#L225
- https://github.com/photoprism/photoprism/issues/1478 

Trace:

```
panic: sync: negative WaitGroup counter

goroutine 3326 [running]:
sync.(*WaitGroup).Add(0xc004761070, 0xffffffffffffffff)
         /usr/local/go/src/sync/waitgroup.go:74 +0x147
 sync.(*WaitGroup).Done(...)
         /usr/local/go/src/sync/waitgroup.go:99
 github.com/mpraski/clusters.(*dbscanClusterer).nearestWorker(0xc000cce3c0)
        /go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:251 +0x230
 created by github.com/mpraski/clusters.(*dbscanClusterer).startNearestWorkers
         /go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:228
```

**Comment by montanaflynn** [comment]
Hello, I think the library you're looking for is https://github.com/mpraski/clusters

**Comment by lastzero** [comment]
Sorry!

**Comment by montanaflynn** [comment]
No problem, photoprism looks like a great project and I was happy to find it for my own use!

**Comment by lastzero** [comment]
Seems we're also using your library, not for clustering though. Thus the confusion! 😜
