### ISSUE TITLE
Trouble with trying to add Changelog and Documentation

### ISSUE THREAD

**Issue by SamuelDixxon** [montanaflynn/stats#74]
Hello, I wanted to try and practice some of the go programming language, while contributing to an open source package. I was able to write some functions and test those functions utilizing the makefile provided. However, I had trouble trying to get the packages for changelog / documention . MD file updates

go get github.com/davecheney/godoc2md
go get github.com/golangci/golangci-lint/cmd/golangci-lint

I ran the top command and had some errors, which I believe yielded me in errors for running the bottom command. I checked the top repository and it looks like it is no longer being developed. 

I've never contributed in this way and don't have experience in making the edits to the markdown files, but am trying to learn more of all things git and software.

**Comment by montanaflynn** [comment]
Hello @SamuelDixxon, thanks for contribution and interest!

What errors did you get? They worked for me (`go version go1.18.3 darwin/arm64`)

```shell
~/D/stats master• 1.6s ❱ go get github.com/davecheney/godoc2md
go: downloading github.com/davecheney/godoc2md v0.0.0-20190217193848-4eed58d98896
go: downloading golang.org/x/tools v0.0.0-20181011021141-0e57ebad1d6b
go: added github.com/davecheney/godoc2md v0.0.0-20190217193848-4eed58d98896

~/D/stats master• 4.3s ❱ go get github.com/golangci/golangci-lint/cmd/golangci-lint
go: downloading github.com/golangci/golangci-lint v1.50.1
go: downloading github.com/gofrs/flock v0.8.1
...
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: added github.com/golangci/golangci-lint v1.50.1
```

**Comment by SamuelDixxon** [comment]
@montanaflynn 
I get the following errors 
![image](https://user-images.githubusercontent.com/61887299/210930828-3f7896fb-0716-499a-b495-1c7743ff615e.png)

![image](https://user-images.githubusercontent.com/61887299/210931368-6acb68da-9b28-4444-8742-2d72b70aebca.png)

**Comment by montanaflynn** [comment]
Can you try updating go to a more recent version?

**Comment by SamuelDixxon** [comment]
Thanks, I got the latest version and was able to get those packages, but am now stuck trying to run the make command to run the make doc command.
![image](https://user-images.githubusercontent.com/61887299/210938585-4d257cc1-1944-425f-b704-a55a5228afcc.png)

**Comment by montanaflynn** [comment]
I found the problem, at some point Golang changed how to install tools from `go get` to `go install`.

```
go install github.com/davecheney/godoc2md@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
```

However these commands are not needed to contribute, only for releasing new versions.

For contribution steps see: https://github.com/montanaflynn/stats#contributing

I really have the [releasing section](https://github.com/montanaflynn/stats#releasing) in the README.md mostly for myself or as a resource for others who want to maintain their own library, but it's not required for contributors, and in fact cannot be used since you won't have permission for `make release`.

**Comment by SamuelDixxon** [comment]
Okay, thanks for the help!
