### ISSUE TITLE
CumulativeSum doesn't exist

### ISSUE THREAD

**Issue by JourneyToSilius** [montanaflynn/stats#82]
It's on the readme, but it's not in the package

**Comment by montanaflynn** [comment]
It's been there for 6 years, https://pkg.go.dev/github.com/montanaflynn/stats#CumulativeSum

What version of the package are you using? Are you seeing some error when trying to use it?

**Comment by JourneyToSilius** [comment]
when I do import and get / tidy my .mod looks like this  : 	
`github.com/montanaflynn/stats v0.0.0-20171201202039-1bf9dbcd8cbe`
